services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: racky-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: racky
    volumes:
      - mongodb_dev_data:/data/db
      - mongodb_dev_config:/data/configdb
    networks:
      - racky-dev-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: racky-rabbitmq-dev
    restart: unless-stopped
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI
    volumes:
      - rabbitmq_dev_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: racky
      RABBITMQ_DEFAULT_PASS: racky123
      RABBITMQ_DEFAULT_VHOST: racky
    networks:
      - racky-dev-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 5s
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  mongodb_dev_data:
    driver: local
  mongodb_dev_config:
    driver: local
  rabbitmq_dev_data:
    driver: local

networks:
  racky-dev-network:
    driver: bridge
