aws:
  region: "us-east-1-"
  default_region: "us-east-1"

node_selector: "prodNodes"

subdomain: "rackyapp"

secrets:
  path: prod

hpa:
  replicaCount: 
    min: "1"
    max: "3"

mongodb:
  username: mongorckadmin
  host: customer-panel-prod.2uuzuli.mongodb.net

stripe:
  public_key: "pk_test_51OKRPyCAwpKOzXIuhLuw1aFrtrXmGIbTzkaZIPFNDEiIe6bQQ3k9mwcricGx1P0Zjx0y2mdcLGWgIUyHPEn1VrHU00bQZKT3rf"