aws:
  region: "us-east-1-"
  default_region: "us-east-1"

node_selector: "prodNodes"

subdomain: "suite"

frontend_url: "https://suite.racky.ai"

secrets:
  path: prod

hpa:
  replicaCount: 
    min: "1"
    max: "3"

mongodb:
  username: mongorckadmin
  host: customer-panel-prod.2uuzuli.mongodb.net

stripe:
  public_key: "pk_live_51MJP0zFwwa3TZj14oIJ3IYTWce9BbA9LIbVB19YEPisD3Ia77n9SiVOjwhtSDlRtXDbmqENPaTnjBW3VtK8nien300goi4cuSg"