apiVersion: v1
data:
  BACKEND_PORT: 5000
  NODE_ENV: development
  FRONTEND_PORT: 5173
  VITE_API_URL: http://localhost:5000/api
  CLIENT_URL: http://localhost:5173
  #MONGODB_DATABASE: {{ .Values.mongodb.username }}
  #MONGODB_URI: {{ .Values.mongodb.host }}
  USE_RABBITMQ: "true"
  MONGODB_URI: mongodb://mongodb.app:27017/racky
  MONGODB_PORT: 55007
  MONGODB_DATABASE: racky
  RABBITMQ_VHOST: racky
  RABBITMQ_PORT: 5672
  RABBITMQ_MGMT_PORT: 15672
  RABBITMQ_MGMT_URL: http://rabbitmq.app:15672
  VITE_STRIPE_PUBLISHABLE_KEY: {{ .Values.stripe.public_key }}
  CLIENT_URL: http://localhost:5173
kind: ConfigMap
metadata:
  name: racky-app-env
  namespace: {{ .Values.environment }}