---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: racky-app
  labels:
    app: racky-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: racky-app
  template:
    metadata:
      labels:
        app: racky-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - racky-app
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: backend
        image: "{{ .Values.aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/rackoot/racky.app.backend:{{ .Values.app_version }}"
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: racky-app-secrets
        - configMapRef:
            name: racky-app-env
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /startup
            port: 3005
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 30
      - name: frontend
        image: "{{ .Values.aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com/rackoot/racky.app.frontend:{{ .Values.app_version }}"
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: racky-app-secrets
        - configMapRef:
            name: racky-app-env
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      - name: mongodb-app
        image: "mongo:7.0"
        imagePullPolicy: Always
      - name: rabbitmq-app
        image: "rabbitmq:3.13-management-alpine"
        imagePullPolicy: Always
      nodeSelector:
        eks.amazonaws.com/nodegroup: {{ .Values.node_selector }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: rackoot-iam
      serviceAccountName: rackoot-iam