apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: racky-app-secrets
  namespace: {{ .Values.environment }}
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default 
      decodingStrategy: None
      key: {{ .Values.secrets.path }}/racky.app
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: rackoot-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: racky-app-secrets
